spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: 1.0

loans:
  message: "Welcome to EazyBank loans related PRODUCTIONN APIs "
  contactDetails:
    name: "Smitha Ray - PROD Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371